name: Run ClockOut

on:
  schedule:
    - cron:  '10 9 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run
      run: go run Out/main.go
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        LAT: ${{ secrets.LAT }}
        LONG: ${{ secrets.LONG }}
      
